points:
    key:
        padding: cy
    zones:
        main:
            rows:
                bottom:
                home:
                top:
            columns:
                pinky:
                    key:
                        spread: cx
                    rows:
                        bottom:
                            col_net: P21
                        home:
                            col_net: P20
                        top:
                            col_net: P19
                ring:
                    key:
                        stagger: 4
                        spread: cx
                    rows:
                        bottom:
                            col_net: P18
                        home:
                            col_net: P15
                        top:
                            col_net: P14
                middle:
                    key:
                        stagger: 2
                        spread: cx
                    rows:
                        bottom:
                            col_net: P16
                        home:
                            col_net: P10
                        top:
                            col_net: P1
                index:
                    key:
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            col_net: P0
                        home:
                            col_net: P2
                        top:
                            col_net: P3
                inner:
                    key:
                        stagger: -2
                        spread: cx
                    rows:
                        bottom:
                            col_net: P4
                        home:
                            col_net: P5
                        top:
                            col_net: P6
        thumb:
            anchor:
                ref: main_index_bottom
                shift: [-0.5cx, -cy]
            rows:
                home:
            columns:
                inner.key:
                    col_net: P7
                    spread: cx
                home.key:
                    col_net: P8
                    spread: cx + 2
                    rotate: -18
                    stagger: -3.2
                outer.key:
                    col_net: P9
                    spread: cx
                    rotate: -36
                    stagger: -9.2
outlines:
    _board_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: thumb_outer_home
                    shift: [0.6cx, 0.6cy]
                -   ref: thumb_outer_home
                    shift: [0.6cx, -0.6cy]
                -   ref: thumb_outer_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: thumb_home_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_home_home
                    shift: [-0.4cx, -0.6cy]

                -   ref: thumb_inner_home
                    shift: [0.4cx, -0.6cy]
                -   ref: thumb_inner_home
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_pinky_bottom
                    shift: [1.6cx, -0.6cy]
                -   ref: main_pinky_bottom
                    shift: [0.6cx, -0.6cy]
                -   ref: main_pinky_bottom
                    shift: [-0.6cx, -0.6cy]

                -   ref: main_pinky_top
                    shift: [-0.6cx, 0.6cy]
                -   ref: main_pinky_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_ring_top
                    shift: [-0.5cx, 0.6cy]
                -   ref: main_ring_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_middle_top
                    shift: [-0.4cx, 0.61cy]
                -   ref: main_middle_top
                    shift: [0.4cx, 0.6cy]

                -   ref: main_index_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_index_top
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_top
                    shift: [-0.4cx, 0.6cy]
                -   ref: main_inner_top
                    shift: [0.5cx, 0.6cy]

                -   ref: main_inner_top
                    shift: [0.6cx, 0.4cy]
                -   ref: main_inner_top
                    shift: [1.8cx, 0.4cy]

                -   ref: main_inner_bottom
                    shift: [1.8cx, -0.6cy]
    _keycap_outlines:
        -   what: rectangle
            fillet: 2
            where: true
            size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
    preview:
        -   what: outline
            name: _board_outline
            operation: stack
        -   what: outline
            name: _keycap_outlines
            operation: stack
cases.vee_board:
    -   what: outline
        name: _board_outline
        extrude: 3
        operation: subtract
    -   what: outline
        name: _keycap_outlines
        extrude: 6
        operation: add
pcbs.vee_board:
    outlines:
        main.outline: _board_outline
        keycaps:
            outline: _keycap_outlines
            layer: Eco1.User
    footprints:
        choc_hotswap:
            what: choc
            where: true
            params:
                from: "{{col_net}}"
                to: GND
                keycaps: true
                reverse: true
                hotswap: true
        choc:
            what: choc
            where: true
            adjust:
                rotate: 180
            params:
                from: "{{col_net}}"
                to: GND
                keycaps: true
                reverse: true             
        promicro:
            what: promicro_pretty # can use a NRF52840 Nice!Nano
            where:
                ref: main_inner_home
            adjust:
                shift: [22, 6.5]
                rotate: -90
        jst-s2b-ph-kl: # jst battery connector
            what: jst-s2b-ph-kl
            where:
                ref: main_inner_bottom
                shift: [21, -5]
                rotate: 180
            params:
                neg: GND
        pcm12:
            what: pcm12 # power switch
            where:
                ref: main_inner_bottom
                shift: [30.5, 3]
                rotate: 90
            params:
                from: pos
                to: RAW
        wuerth-434121025816: # reset switch
            what: wuerth-434121025816
            where:
                ref: main_inner_bottom
                shift: [30, -6]
                rotate: 90
            params:
                r1: RST
                r2: GND
        front_text: &text
            what: text
            where: &textWhere
                ref: main_pinky_bottom
                shift: [12, -7]
            params: &textParams
                text: vee_board\nby v_Zak
                justify: left
        back_text:
            <<: *text
            where:
                <<: *textWhere
                shift: [27, -7]
            params:
                <<: *textParams
                layer: B.SilkS
                justify: left mirror    

